import Footer from "@/components/Footer";
import Header from "@/components/Header";
import SingUpScoop from "@/components/SingUpScoop";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LWS Shop Center",
  description: "Generated by create next app",
};

export default function SameLayout({ children }) {
  return (
    <>
      <Header />
      {children}
      <SingUpScoop />
      <Footer />
    </>
  );
}
